### ISSUE TITLE
Breaks media keys for Spotify

### ISSUE THREAD

**Issue by HappyGhetto** [root670/Soundcloud-Media-Keys#1]
If it's not possible to fix, would it be possible to make the extension icon disable the extension on left click so you don't have to go into settings and disable it? Thanks for making this though, haven't found this anywhere else.

**Comment by root670** [comment]
Thank you for the suggestion! I will look into implementing a way to unmap the media keys from Chrome so other applications can access them.

**Comment by root670** [comment]
Unfortunately there doesn't seem to be a way of remapping commands or unmapping commands from within the plugin. The only work around for this is to disable the plugin when using another application that uses the media keys, or remap the commands to buttons other than the media keys.
